apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-page1
        image: nginx
        ports:
        - containerPort: 80
      - name: nginx-page2
        image: nginx
        ports:
        - containerPort: 80
      volumes:
        - name: nginx-volumes
          persistentVolumeClaim:
            claimName: nginx